wercker: add java installation

diff --git a/wercker.yml b/wercker.yml
--- a/wercker.yml
+++ b/wercker.yml
@@ -5,19 +5,50 @@ build:
             name: setup
             code: |
               sudo apt-get update -y
-              sudo apt-get -y install maven
-              sudo apt-get -y install ruby
-              sudo apt-get -y install ruby-dev
+        - install-packages:
+            packages: maven ruby ruby-dev bzr mercurial git wget
+        - script:
+            name: install java
+            code: |-
+              # Remove java from base box
+              sudo apt-get purge openjdk-\* icedtea-\* icedtea6-\*
+              
+              # Assert that java is not available anymore
+              ! type java || { echo "I expected java to be not available. Java version is: $(java -version). Aborting."; exit 1; }
+
+              # Add webupd8 team repository that contains the 3 major oracle-java versions
+              sudo add-apt-repository ppa:webupd8team/java -y
+              sudo apt-get update
+
+              # Accept the oracle license
+              echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
+              echo debconf shared/accepted-oracle-license-v1-1 seen true |  sudo debconf-set-selections
+              
+              # Install oracle-java7
+              sudo apt-get install oracle-java7-installer -y -qq
+              
+              # We should have java again
+              type java || { echo "I expected java to be available after oracle-java7-installer installation. Aborting."; exit 1; }
+
+              # Install ant
+              sudo apt-get install ant ant-contrib ivy ivy-doc -y -qq
+              
+              # We should have ant and ivy available
+              type ant || { echo "I expected ant to be available. Aborting."; exit 1; }
+
+              # Install maven
+              sudo apt-get install maven -y -qq
+              
+              type mvn || { echo "I expected maven to be available. Aborting."; exit 1; }
+        - script:
+            name: setup
+            code: |
               sudo gem install bundle --no-ri --no-rdoc
               sudo gem install rake --no-ri --no-rdoc
               sudo gem install serverspec --no-ri --no-rdoc
               
               # Install golang
               version="1.3.1"
-              sudo apt-get -y  install bzr
-              sudo apt-get -y  install mercurial
-              sudo apt-get -y  install git
-              sudo apt-get -y  install wget
               wget http://golang.org/dl/go${version}.linux-amd64.tar.gz
               sudo tar -C /usr/local -xzf go${version}.linux-amd64.tar.gz
               echo "export PATH=$PATH:/usr/local/go/bin" | sudo tee -a /etc/profile
